#PBS -A d171-s1951167
#PBS -N percolate
#PBS -j oe
#PBS -l walltime=00:05:00
#PBS -l place=excl

# You will need to change the value of "select" below if you run on
# more than 36 processes; the value of "ncpus" *is always 36*.

#PBS -l select=1:ncpus=36




# Change directory back to where the job was submitted from

cd $PBS_O_WORKDIR

./percolate_2 1564 288
./percolate_2 1564 576
./percolate_2 1564 864
./percolate_2 1564 1152
./percolate_2 1564 1728


