#PBS -A d171-s1951167
#PBS -N percolate
#PBS -j oe
#PBS -l walltime=00:10:00
#PBS -l place=excl

# You will need to change the value of "select" below if you run on
# more than 36 processes; the value of "ncpus" *is always 36*.

#PBS -l select=2:ncpus=36

module load mpt
module load intel-compilers-18


# Change directory back to where the job was submitted from

cd $PBS_O_WORKDIR
echo '------rho = 0.2------'
echo '-------203-----------'

mpiexec_mpt -ppn 36 -n 1 ./percolate203_2 1564


